<?php
/**
 * Immutable product boundary for the WordPress.org package.
 *
 * No option, filter, signed policy or response from an external service can
 * enable application of externally generated executable changes.
 *
 * @package AI_Bug_Hunter
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class ABH_Edition {

	const ID = 'wordpress-org';

	public static function can_apply_external_repairs() {
		return false;
	}

	public static function has_commercial_services() {
		return false;
	}

	public static function normalize_ai_result( $result ) {
		if ( ! is_array( $result ) ) {
			return $result;
		}
		$result['apply_allowed']          = false;
		$result['assisted_apply_allowed'] = false;
		$result['can_prepare_assisted']   = false;
		$result['manual_guide_available'] = true;
		$result['edition']                = self::ID;
		$result['export_only']            = true;
		return $result;
	}

	public static function application_refused() {
		return array(
			'ok'          => false,
			'export_only' => true,
			'message'     => __( 'The WordPress.org edition only analyzes and lets you review or export the proposal. It cannot apply executable changes generated by an external service.', 'ai-bug-hunter' ),
		);
	}
}
