<?php
/**
 * Read-only policy used by the WordPress.org edition.
 *
 * This file intentionally contains no implementation capable of changing a
 * site file. It preserves the path, proposal, and compatibility APIs used by
 * the diagnostic pipeline while making every application request fail closed.
 *
 * @package AI_Bug_Hunter
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Public-edition product limits.
 */
final class ABH_Limits {

	/**
	 * Critical WordPress bootstrap files excluded from proposals.
	 *
	 * @return array
	 */
	public static function never() {
		return array( 'wp-config.php', 'wp-settings.php', 'wp-load.php', 'wp-blog-header.php' );
	}

	/**
	 * The public edition does not maintain a special executable-file list.
	 *
	 * @return array
	 */
	public static function dropins() {
		return array();
	}

	/**
	 * Relative content directory.
	 *
	 * @return string
	 */
	public static function content_rel() {
		$root = wp_normalize_path( ABSPATH );
		$dir  = wp_normalize_path( WP_CONTENT_DIR );
		if ( 0 === strpos( $dir, trailingslashit( $root ) ) ) {
			return trim( substr( $dir, strlen( trailingslashit( $root ) ) ), '/' );
		}
		return 'wp-content';
	}

	/**
	 * Compatibility method retained for read-only callers.
	 *
	 * @param string $path Relative path.
	 * @return bool
	 */
	public static function is_dropin( $path ) {
		unset( $path );
		return false;
	}

	/**
	 * Whether a path is excluded from proposals.
	 *
	 * @param string $path Relative or absolute path.
	 * @return bool
	 */
	public static function is_never( $path ) {
		$base = strtolower( basename( str_replace( '\\', '/', (string) $path ) ) );
		return in_array( $base, self::never(), true );
	}

	/**
	 * The analysis-only edition has no removable special files.
	 *
	 * @return array
	 */
	public static function removable() {
		return array();
	}

	/**
	 * Compatibility method for legacy callers.
	 *
	 * @param string $path Relative path.
	 * @return bool
	 */
	public static function is_removable( $path ) {
		unset( $path );
		return false;
	}

	/**
	 * Capabilities shown on the Settings screen.
	 *
	 * @return array
	 */
	public static function operations() {
		return array(
			'inspect' => array(
				'titulo'    => __( 'Inspect and compare source files', 'ai-bug-hunter' ),
				'alcance'   => __( 'PHP files related to a recorded incident.', 'ai-bug-hunter' ),
				'porque'    => __( 'Reading the deployed source provides the evidence needed for a useful diagnosis.', 'ai-bug-hunter' ),
				'consiente' => __( 'External communication still requires explicit consent.', 'ai-bug-hunter' ),
				'revertir'  => __( 'Not applicable: inspection changes nothing.', 'ai-bug-hunter' ),
				'enforcer'  => 'ABH_Guard::check_path',
			),
			'propose' => array(
				'titulo'    => __( 'Prepare a reviewable proposal', 'ai-bug-hunter' ),
				'alcance'   => __( 'A line-by-line difference and a plain-language repair guide.', 'ai-bug-hunter' ),
				'porque'    => __( 'The administrator can review the evidence and perform the work through their normal maintenance process.', 'ai-bug-hunter' ),
				'consiente' => __( 'Yes, before contacting the selected AI provider.', 'ai-bug-hunter' ),
				'revertir'  => __( 'Not applicable: the proposal is not applied.', 'ai-bug-hunter' ),
				'enforcer'  => 'ABH_Edition::can_apply_external_repairs',
			),
			'export' => array(
				'titulo'    => __( 'Export the diagnosis or proposal', 'ai-bug-hunter' ),
				'alcance'   => __( 'Reports and real line-by-line differences created for review.', 'ai-bug-hunter' ),
				'porque'    => __( 'Exports help a site owner or developer complete the repair outside this plugin.', 'ai-bug-hunter' ),
				'consiente' => __( 'The administrator starts the download.', 'ai-bug-hunter' ),
				'revertir'  => __( 'Not applicable: downloading a report changes nothing on the site.', 'ai-bug-hunter' ),
				'enforcer'  => '',
			),
		);
	}

	/**
	 * Immutable promises for the public edition.
	 *
	 * @return array
	 */
	public static function will_not() {
		return array(
			__( 'It does not apply a proposal generated by an external AI provider.', 'ai-bug-hunter' ),
			__( 'It does not alter the incident file while preparing a diagnosis or difference.', 'ai-bug-hunter' ),
			__( 'It does not activate or deactivate themes or extensions.', 'ai-bug-hunter' ),
			__( 'It does not change users, orders, posts, or other site content.', 'ai-bug-hunter' ),
			__( 'It does not contact an AI provider before the administrator explicitly opts in.', 'ai-bug-hunter' ),
		);
	}

	/**
	 * Administrator responsibilities.
	 *
	 * @return array
	 */
	public static function responsibility() {
		return array(
			__( 'Review the diagnosis and proposed difference before changing production files.', 'ai-bug-hunter' ),
			__( 'Keep a complete site backup and test repairs in a staging environment whenever possible.', 'ai-bug-hunter' ),
			__( 'AI analysis can be wrong; confirm the evidence and follow the developer\'s documentation.', 'ai-bug-hunter' ),
		);
	}
}

/**
 * Read-only path and proposal validator.
 */
final class ABH_Guard {

	/**
	 * Files excluded from proposals.
	 *
	 * @return array
	 */
	public static function protected_files() {
		return ABH_Limits::never();
	}

	/**
	 * Core directories excluded from free-form proposals.
	 *
	 * @return array
	 */
	public static function core_dirs() {
		return array( 'wp-admin/', 'wp-includes/' );
	}

	/**
	 * Human-readable validation catalog.
	 *
	 * @return array
	 */
	public static function catalog() {
		return array(
			'BH-PUBLIC-001' => array(
				'titulo'       => __( 'Protected WordPress path', 'ai-bug-hunter' ),
				'explicacion'  => __( 'This path is outside the proposal scope of the public edition.', 'ai-bug-hunter' ),
				'apelable'     => false,
				'consecuencia' => 'rechazo',
			),
			'BH-PUBLIC-002' => array(
				'titulo'       => __( 'Invalid or unsupported path', 'ai-bug-hunter' ),
				'explicacion'  => __( 'The path could not be resolved safely inside the WordPress installation.', 'ai-bug-hunter' ),
				'apelable'     => false,
				'consecuencia' => 'rechazo',
			),
			'BH-PUBLIC-003' => array(
				'titulo'       => __( 'Incomplete proposal', 'ai-bug-hunter' ),
				'explicacion'  => __( 'The proposed result omits too much of the original file to be reviewed safely.', 'ai-bug-hunter' ),
				'apelable'     => false,
				'consecuencia' => 'rechazo',
			),
			'BH-PUBLIC-004' => array(
				'titulo'       => __( 'Broad proposal', 'ai-bug-hunter' ),
				'explicacion'  => __( 'A large portion of the file differs. Review the complete proposal carefully.', 'ai-bug-hunter' ),
				'apelable'     => true,
				'consecuencia' => 'aviso',
			),
		);
	}

	/**
	 * Compatibility consequence value.
	 *
	 * @param array $finding Finding.
	 * @return string
	 */
	public static function consequence( $finding ) {
		$info = self::describe( $finding );
		return isset( $info['consecuencia'] ) ? (string) $info['consecuencia'] : 'rechazo';
	}

	/**
	 * Normalize a relative path.
	 *
	 * @param string $path Path.
	 * @return string
	 */
	public static function normalize( $path ) {
		$path  = str_replace( '\\', '/', (string) $path );
		$path  = ltrim( $path, '/' );
		$parts = array();
		foreach ( explode( '/', $path ) as $segment ) {
			if ( '' === $segment || '.' === $segment ) {
				continue;
			}
			if ( '..' === $segment ) {
				if ( empty( $parts ) ) {
					return '..';
				}
				array_pop( $parts );
				continue;
			}
			$parts[] = $segment;
		}
		return implode( '/', $parts );
	}

	/**
	 * Check a relative directory boundary.
	 *
	 * @param string $path Path.
	 * @param string $root Root.
	 * @return bool
	 */
	public static function path_in_root( $path, $root ) {
		$path = trim( self::normalize( $path ), '/' );
		$root = trim( self::normalize( $root ), '/' );
		return '' !== $path && '' !== $root && ( $path === $root || 0 === strpos( $path, $root . '/' ) );
	}

	/**
	 * Check an absolute directory boundary.
	 *
	 * @param string $path Path.
	 * @param string $root Root.
	 * @return bool
	 */
	public static function absolute_in_root( $path, $root ) {
		$path = rtrim( wp_normalize_path( (string) $path ), '/' );
		$root = rtrim( wp_normalize_path( (string) $root ), '/' );
		return '' !== $path && '' !== $root && ( $path === $root || 0 === strpos( $path, $root . '/' ) );
	}

	/**
	 * Resolve an existing path without following a link outside WordPress.
	 *
	 * @param string     $rel_path Relative path.
	 * @param array|null $roots    Optional allowed roots.
	 * @return string|false
	 */
	public static function resolve_existing_path( $rel_path, $roots = null ) {
		$rel = self::normalize( $rel_path );
		if ( '' === $rel || '..' === $rel || false !== strpos( str_replace( '\\', '/', (string) $rel_path ), '..' ) ) {
			return false;
		}
		if ( is_array( $roots ) && empty( self::check_path( $rel, $roots )['allowed'] ) ) {
			return false;
		}
		$base = realpath( ABSPATH );
		if ( false === $base ) {
			return false;
		}
		$current = rtrim( wp_normalize_path( ABSPATH ), '/' );
		foreach ( explode( '/', $rel ) as $segment ) {
			$current .= '/' . $segment;
			if ( is_link( $current ) ) {
				return false;
			}
		}
		$resolved = realpath( $current );
		if ( false === $resolved || ! self::absolute_in_root( $resolved, $base ) ) {
			return false;
		}
		return wp_normalize_path( $resolved );
	}

	/**
	 * Validate a proposal path.
	 *
	 * @param string $rel_path Relative path.
	 * @param array  $roots    Allowed roots.
	 * @return array
	 */
	public static function check_path( $rel_path, $roots = array( 'wp-content/' ) ) {
		$raw = str_replace( '\\', '/', (string) $rel_path );
		$rel = self::normalize( $raw );
		if ( '' === $rel || '..' === $rel || false !== strpos( $raw, '..' ) ) {
			return self::deny( 'BH-PUBLIC-002', $rel_path );
		}
		$leaf = basename( $rel );
		if ( $leaf !== rtrim( $leaf, ". \t" ) || false !== strpos( $leaf, ':' ) ) {
			return self::deny( 'BH-PUBLIC-002', $rel );
		}
		if ( ABH_Limits::is_never( $rel ) ) {
			return self::deny( 'BH-PUBLIC-001', $rel );
		}
		foreach ( self::core_dirs() as $dir ) {
			if ( 0 === strpos( $rel, $dir ) ) {
				return self::deny( 'BH-PUBLIC-001', $rel );
			}
		}
		$inside = empty( $roots );
		foreach ( (array) $roots as $root ) {
			if ( self::path_in_root( $rel, $root ) ) {
				$inside = true;
				break;
			}
		}
		if ( ! $inside ) {
			return self::deny( 'BH-PUBLIC-002', $rel );
		}
		return array( 'allowed' => true, 'advisory_only' => false, 'findings' => array() );
	}

	/**
	 * Compatibility wrapper for operation-aware callers.
	 *
	 * @param string $rel_path Relative path.
	 * @param array  $roots    Allowed roots.
	 * @param string $type     Requested operation.
	 * @return array
	 */
	public static function check_path_op( $rel_path, $roots = array( 'wp-content/' ), $type = 'escribir' ) {
		unset( $type );
		return self::check_path( $rel_path, $roots );
	}

	/**
	 * Validate proposal completeness without maintaining hazardous signatures.
	 *
	 * @param string $original Original source.
	 * @param string $patched  Proposed source.
	 * @return array
	 */
	public static function check_content( $original, $patched ) {
		$findings = array();
		$diff     = self::added_removed( $original, $patched );
		$old_n    = count( explode( "\n", (string) $original ) );
		$new_n    = count( explode( "\n", (string) $patched ) );
		if ( $old_n > 80 && $new_n < (int) ( $old_n * 0.5 ) ) {
			$findings[] = array( 'code' => 'BH-PUBLIC-003', 'severity' => 'block', 'evidence' => sprintf( __( '%1$d original lines and %2$d proposed lines', 'ai-bug-hunter' ), $old_n, $new_n ), 'line' => 0 );
		}
		if ( $old_n > 20 && ( count( $diff['added'] ) / max( 1, $old_n ) ) > 0.60 ) {
			$findings[] = array( 'code' => 'BH-PUBLIC-004', 'severity' => 'warn', 'evidence' => __( 'Most of the file differs from the original.', 'ai-bug-hunter' ), 'line' => 0 );
		}
		$blocked = false;
		foreach ( $findings as $finding ) {
			if ( 'block' === $finding['severity'] ) {
				$blocked = true;
				break;
			}
		}
		return array( 'allowed' => ! $blocked, 'advisory_only' => false, 'findings' => $findings );
	}

	/**
	 * Calculate a compact line-level difference.
	 *
	 * @param string $original Original source.
	 * @param string $patched  Proposed source.
	 * @return array
	 */
	public static function added_removed( $original, $patched ) {
		$old       = explode( "\n", str_replace( "\r\n", "\n", (string) $original ) );
		$new       = explode( "\n", str_replace( "\r\n", "\n", (string) $patched ) );
		$old_count = array_count_values( array_map( 'trim', $old ) );
		$new_count = array_count_values( array_map( 'trim', $new ) );
		$added     = array();
		$removed   = array();
		foreach ( $new as $index => $line ) {
			$key = trim( $line );
			if ( ( isset( $new_count[ $key ] ) ? $new_count[ $key ] : 0 ) > ( isset( $old_count[ $key ] ) ? $old_count[ $key ] : 0 ) ) {
				$added[] = array( 'line' => $index + 1, 'text' => $line );
			}
		}
		foreach ( $old as $line ) {
			$key = trim( $line );
			if ( ( isset( $old_count[ $key ] ) ? $old_count[ $key ] : 0 ) > ( isset( $new_count[ $key ] ) ? $new_count[ $key ] : 0 ) ) {
				$removed[] = $line;
			}
		}
		return array( 'added' => $added, 'removed' => $removed );
	}

	/**
	 * Add catalog information to a finding.
	 *
	 * @param array $finding Finding.
	 * @return array
	 */
	public static function describe( $finding ) {
		$catalog = self::catalog();
		$code    = isset( $finding['code'] ) ? (string) $finding['code'] : '';
		$info    = isset( $catalog[ $code ] ) ? $catalog[ $code ] : array( 'titulo' => $code, 'explicacion' => '', 'apelable' => false, 'consecuencia' => 'rechazo' );
		return array_merge( $finding, $info );
	}

	/**
	 * Build a failed validation result.
	 *
	 * @param string $code     Catalog code.
	 * @param string $evidence Evidence.
	 * @return array
	 */
	private static function deny( $code, $evidence ) {
		return array(
			'allowed'       => false,
			'advisory_only' => true,
			'findings'      => array( array( 'code' => $code, 'severity' => 'block', 'evidence' => (string) $evidence, 'line' => 0 ) ),
		);
	}
}

/**
 * Preview-plan compatibility layer.
 */
final class ABH_Transaction {

	const FLAG     = 'ABH_MULTIFILE';
	const OPS      = array( 'escribir', 'mover', 'quitar', 'permisos' );
	const DIR_UNDO = 'wp-content/abh-txn';
	const DIARIO   = 'abh_txn_journal';

	/**
	 * Application is permanently disabled in this edition.
	 *
	 * @return bool
	 */
	public static function enabled() {
		return false;
	}

	/**
	 * Create a correlation identifier for an in-memory preview.
	 *
	 * @return string
	 */
	public static function new_txn_id() {
		return 'PREVIEW-' . gmdate( 'Ymd-His' ) . '-' . wp_generate_password( 6, false, false );
	}

	/**
	 * Build a review-only multi-file payload.
	 *
	 * @param string $txn_id Identifier.
	 * @param array  $files  Proposed files.
	 * @param array  $meta   Metadata.
	 * @return array
	 */
	public static function build_payload( $txn_id, $files, $meta = array() ) {
		$clean = array();
		$seen  = array();
		foreach ( (array) $files as $file ) {
			if ( empty( $file['rel_path'] ) || ! isset( $file['patched'] ) || empty( $file['sha_before'] ) ) {
				return self::failure( __( 'One file in the preview is incomplete.', 'ai-bug-hunter' ), 'preview_build' );
			}
			$rel   = ABH_Guard::normalize( $file['rel_path'] );
			$check = ABH_Guard::check_path( $rel, array( ABH_Limits::content_rel() ) );
			if ( empty( $check['allowed'] ) || isset( $seen[ $rel ] ) ) {
				return self::failure( __( 'The preview contains an invalid or repeated path.', 'ai-bug-hunter' ), 'preview_build' );
			}
			$seen[ $rel ] = true;
			$clean[]      = array(
				'rel_path'    => $rel,
				'sha_before'  => (string) $file['sha_before'],
				'patched'     => (string) $file['patched'],
				'diff'        => isset( $file['diff'] ) && is_array( $file['diff'] ) ? $file['diff'] : array(),
				'edits'       => isset( $file['edits'] ) && is_array( $file['edits'] ) ? $file['edits'] : array(),
				'explicacion' => isset( $file['explicacion'] ) && is_array( $file['explicacion'] ) ? $file['explicacion'] : array(),
			);
		}
		if ( empty( $clean ) ) {
			return self::failure( __( 'The preview does not contain any files.', 'ai-bug-hunter' ), 'preview_build' );
		}
		$payload = array(
			'version'       => 2,
			'txn_id'        => (string) $txn_id,
			'files'         => $clean,
			'apply_allowed' => false,
			'phase'         => 'preview',
			'export_only'   => true,
		);
		return array( 'ok' => true, 'payload' => array_merge( $payload, (array) $meta, array( 'apply_allowed' => false, 'export_only' => true ) ) );
	}

	/**
	 * Operation-only plans require a manual guide in the public edition.
	 *
	 * @param string $txn_id Identifier.
	 * @param array  $ops    Operations.
	 * @param array  $meta   Metadata.
	 * @return array
	 */
	public static function plan( $txn_id, $ops, $meta = array() ) {
		unset( $txn_id, $ops, $meta );
		return self::failure( __( 'This proposal cannot be represented as a safe line-by-line difference. Use the manual repair guide instead.', 'ai-bug-hunter' ), 'manual_guide' );
	}

	/**
	 * Parse an octal permission value for compatibility with response parsing.
	 *
	 * @param mixed $mode Mode.
	 * @return string|false
	 */
	public static function modo_octal( $mode ) {
		$mode = trim( (string) $mode );
		$mode = preg_replace( '/^0+/', '', $mode );
		if ( ! preg_match( '/^[0-7]{3}$/', $mode ) ) {
			return false;
		}
		return $mode;
	}

	/**
	 * No preview may be applied.
	 *
	 * @param array $payload Payload.
	 * @param bool  $force   Ignored.
	 * @return array
	 */
	public static function apply( $payload, $force = false ) {
		unset( $payload, $force );
		return ABH_Edition::application_refused();
	}

	/**
	 * Refuse every application path before any state changes.
	 *
	 * @param array $payload Payload.
	 * @param bool  $force   Ignored.
	 * @return bool
	 */
	public static function rechazo_seguro( $payload, $force = false ) {
		unset( $payload, $force );
		return true;
	}

	/**
	 * There is no preview storage directory.
	 *
	 * @return false
	 */
	public static function dir_undo() {
		return false;
	}

	/**
	 * Resolve a site-relative path for read-only compatibility.
	 *
	 * @param string $rel Relative path.
	 * @return string|false
	 */
	public static function absolute( $rel ) {
		$rel = ABH_Guard::normalize( $rel );
		if ( '' === $rel || '..' === $rel ) {
			return false;
		}
		$base = trailingslashit( wp_normalize_path( ABSPATH ) );
		$path = $base . $rel;
		return ABH_Guard::absolute_in_root( $path, $base ) ? $path : false;
	}

	/**
	 * No application state exists in the public edition.
	 *
	 * @param string $txn_id Identifier.
	 * @return array
	 */
	public static function estado( $txn_id ) {
		unset( $txn_id );
		return array();
	}

	/**
	 * No rollback operation exists in the public edition.
	 *
	 * @param string $txn_id Identifier.
	 * @return array
	 */
	public static function rollback( $txn_id ) {
		unset( $txn_id );
		return ABH_Edition::application_refused();
	}

	/**
	 * Summarize a preview payload.
	 *
	 * @param array $payload Payload.
	 * @return array
	 */
	public static function summary( $payload ) {
		return array(
			'txn_id'        => isset( $payload['txn_id'] ) ? (string) $payload['txn_id'] : '',
			'files'         => isset( $payload['files'] ) && is_array( $payload['files'] ) ? count( $payload['files'] ) : 0,
			'apply_allowed' => false,
			'export_only'   => true,
		);
	}

	/**
	 * Build a consistent failed preview result.
	 *
	 * @param string $message Message.
	 * @param string $stage   Stage.
	 * @return array
	 */
	private static function failure( $message, $stage ) {
		return array( 'ok' => false, 'stage' => $stage, 'message' => (string) $message, 'export_only' => true );
	}
}
